### PR TITLE
Update node 14

### PR DESCRIPTION
**Pull request by llunaCreixent**
- [x] Update subgraph version after releasing https://github.com/CirclesUBI/circles-subgraph/pull/80

### CODE REVIEW

**Comment by llunaCreixent** [comment]
Now I'm seeing errors in the api-worker which cannot connect to the subgraph.

**Comment by llunaCreixent** [comment]
The subgraph started to not working unexpectedly, and @JacqueGM found out thet it was because the start block cannot be 0. START_BLOCK=0 is the config we've been using for a long time and we never got the error until now.

But finally we fixed it!

Tests pass:
relayer: v4.1.11
api: v1.6.0
contracts: v3.0.1
core: v2.11.1

**Comment by mikozet** [comment]
tested with:
node v15.4.0
npm 7.0.15

**Review by mikozet — APPROVED** [review]

**Review by JacqueGM — DISMISSED** [review]
change the version of the subgraph before merging, other than thaaat LGTM 🌷

**Review by JacqueGM — APPROVED** [review]

**Review by JacqueGM — APPROVED** [review]

**Pull request merged**
