### PR TITLE
update subgraph node

### PR DESCRIPTION
**Pull request by JacqueGM**
- update subgraph to use node 16
- deploy the subraph as a docker image

Related https://github.com/CirclesUBI/circles-docker/issues/76

### CODE REVIEW

**Comment by JacqueGM** [comment]
I see these errors @juanenrisley 
```

 Failed to upload subgraph to IPFS: Failed to upload file to IPFS: AbortController is not defined
Error: Failed to upload file to IPFS: AbortController is not defined
    at Compiler._uploadToIPFS (/Users/jacque/Documents/circles/circles-docker/.tmp/subgraph/node_modules/@graphprotocol/graph-cli/dist/compiler/index.js:463:19)
    at async Compiler._uploadFileToIPFS (/Users/jacque/Documents/circles/circles-docker/.tmp/subgraph/node_modules/@graphprotocol/graph-cli/dist/compiler/index.js:435:26)
    at async /Users/jacque/Documents/circles/circles-docker/.tmp/subgraph/node_modules/@graphprotocol/graph-cli/dist/compiler/index.js:375:24
    at async withSpinner (/Users/jacque/Documents/circles/circles-docker/.tmp/subgraph/node_modules/@graphprotocol/graph-cli/dist/command-helpers/spinner.js:30:24)
    at async Compiler.compile (/Users/jacque/Documents/circles/circles-docker/.tmp/subgraph/node_modules/@graphprotocol/graph-cli/dist/compiler/index.js:103:34)
    at async DeployCommand.run (/Users/jacque/Documents/circles/circles-docker/.tmp/subgraph/node_modules/@graphprotocol/graph-cli/dist/commands/deploy.js:207:28)
    at async DeployCommand._run (/Users/jacque/Documents/circles/circles-docker/.tmp/subgraph/node_modules/@oclif/core/lib/command.js:108:22)
    at async Config.runCommand (/Users/jacque/Documents/circles/circles-docker/.tmp/subgraph/node_modules/@oclif/core/lib/config/config.js:328:25)
    at async Object.run (/Users/jacque/Documents/circles/circles-docker/.tmp/subgraph/node_modules/@oclif/core/lib/main.js:89:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! circles-subgraph@1.4.0 deploy: `./scripts/deploy.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the circles-subgraph@1.4.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jacque/.npm/_logs/2023-04-18T14_20_04_844Z-debug.log
```

**Review by llunaCreixent — DISMISSED** [review]
Amazing!
Everything look perfect, including tests.
Thank you!!

**Comment by juanenrisley** [comment]
@llunaCreixent pls, could you test the local environment with myxogastria, creating an account is enough.

**Review by juanenrisley — APPROVED** [review]
👍🏿

**Review by juanenrisley — APPROVED** [review]

**Pull request merged**
